version: '3.8'

services:
  api:
    build: .
    container_name: deviation-classifier-api
    ports:
      - "8000:8000"
    environment:
      - ABACUS_API_KEY=${ABACUS_API_KEY}
      - DEBUG=${DEBUG:-false}
      - WHISPER_MODEL=${WHISPER_MODEL:-medium}
    volumes:
      # Mount para desenvolvimento (hot reload)
      - ./app:/app/app
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
